review mode_load_save.md again
Oneflow-Inc/oneflow-documentation pull request #247
Opened 2020-08-26 13:59 UTC by Olivert007

1、修改部分大小写
2、增加部分介词

2020-08-26 15:09 UTC, doombeaker commented on en/docs/basics_topics/model_load_save.md
> +)zzzzzzzzzzzzzzzzzzz
这个好像是键盘卡住了？

2020-08-26 15:09 UTC, doombeaker commented on en/docs/basics_topics/model_load_save.md
> +* All sub-directories above have an  `out` document. It stores the parameters of network in binary form. `out` is the default file name. We can change that by `variable op` in the network.
have an  `out`  
out 前多了个空格

2020-08-26 15:10 UTC, doombeaker requested changes
fix typos before merge

2020-08-27 15:10 UTC, Olivert007 commented on en/docs/basics_topics/model_load_save.md
> +* All sub-directories above have an  `out` document. It stores the parameters of network in binary form. `out` is the default file name. We can change that by `variable op` in the network.
已删除

2020-08-27 15:10 UTC, Olivert007 commented on en/docs/basics_topics/model_load_save.md
> +)zzzzzzzzzzzzzzzzzzz
已删除

2020-08-29 09:18 UTC, doombeaker approved these changes

2020-08-29 09:18 UTC, merged