add img2ofrecrd docs and code
Oneflow-Inc/oneflow-documentation pull request #252
Opened 2020-09-17 05:12 UTC by MARD1NO

新增了图片转ofrecord的文档和示例代码

文档中我对于内部编码不太熟悉，应该讲解到什么程度，希望各位能给点建议

2020-09-17 23:07 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +        default='./mnist/train_set',
默认值为 "./mnist/train_set"这种比较生僻，那估计会用不上，改成 "./images" 一类的好点。

2020-09-17 23:09 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +        help='the amount of OFRecord data part')
换成 "number of OFRecord partitions"?

2020-09-17 23:09 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +        default='./mnist/train_label/label.txt',
同上，这样生僻的默认值，约等于不会用上

2020-09-17 23:14 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +            if file_cnt == file_total_cnt // part_num:
特殊情况的检查要考虑，比如用户设置的 part_num 较多，导致 file_total_cnt // part_num == 0，这个会提醒不

2020-09-17 23:16 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +            file_cnt += 1
这个file_cnt 改名为 record_cnt 更合适？

2020-09-17 23:19 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +
把以上封装成 parse_args 和 show_configure 函数，细节隐藏掉

2020-09-17 23:25 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +        labels = label_file.readlines()
我看了下，labels.txt有2W多条真实的记录，这个没必要，改成几十个足够示例就可以了。

2020-09-17 23:28 UTC, doombeaker commented on cn/docs/code/extended_topics/img_to_ofrecord/lenet_train.py
> +if __name__ == "__main__":
这个脚本，感觉可以放到”基础专题“里的”数据输入“那里，作为”数据流水线“的例子，那个文档也可以更新了，我们讨论下。

2020-09-17 23:30 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +- 通过调用 OpenCV 库的 `imdecode` 方法对读取到的**字节流数据**进行解码，**转换成原始图片数据**
mkdocs 的markdown与github的markdown语法略有不同，比如这些星号强调，mdkcos里需要两边留空格。
所以需要自己用mkdocs编译下，看最后效果：切换到cn目录下：
```
mkdocs build
```

2020-09-17 23:31 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +- 制作基于 Mnist 手写数字数据集的 OFRecord 数据集
Mnist -> MNIST ?

2020-09-17 23:32 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +OneFlow 内部的解码算子是采用 [OpenCV](https://opencv.org/) 来对数据进行解码的。相关的 `.cpp` 文件在 [oneflow.user.kernels.ofrecord_decoder_kernels.cpp](https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/user/kernels/o
不应该强调是用什么库，应该强调的是编码格式

2020-09-17 23:35 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +完整代码：[img2ofrecord.py](NULL)
给链接，教对方怎么命令行启动即可。

2020-09-17 23:35 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +完整代码：[img2ofrecord.py](NULL)
链接地址是NULL，记得换成有效的

2020-09-17 23:36 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +- 先用 `bytes_feature` 将图片转化为 `Feature` 格式
感觉这个小节可以和上一个小节合并？讲解流程时，带上关键代码

2020-09-17 23:40 UTC, doombeaker requested changes
labels 2W 条数据太多了，而且它的地位和原始图片是一样的吧，应该放到oss上，而不是github上。
另外labels现在的格式是一行代表一个label，行号对应了文件index？这个用户比较难抽查是否lable正确。
可以改成：
```
file1,label1
file2,label2
...
```
这样或其它格式

2020-09-18 01:20 UTC, MARD1NO commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +        default='./mnist/train_set',
好的我这个重新排一下目录

2020-09-18 01:21 UTC, MARD1NO commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +        help='the amount of OFRecord data part')
amount of OFRecord partitions吧，number感觉怪怪的，像是 “序号” 而不是 “数量”

2020-09-18 01:37 UTC, MARD1NO commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +            if file_cnt == file_total_cnt // part_num:
那我做个简单的检查

2020-09-18 01:39 UTC, MARD1NO commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +
好的，命令行参数和这些print分别封装到两个函数里

2020-09-18 01:41 UTC, MARD1NO commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +            file_cnt += 1
file_cnt是指当前读取图片的计数器，达到预先设置的每一个part的数量后，重新置0计数，写到下一个part内部。不过我想了下前面有个enumerate，这部分应该可以再简化一下的，后续一并修改

2020-09-18 01:42 UTC, MARD1NO commented on cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py
> +        labels = label_file.readlines()
那数据集我重新规整一个出来

2020-09-18 01:44 UTC, MARD1NO commented on cn/docs/code/extended_topics/img_to_ofrecord/lenet_train.py
> +if __name__ == "__main__":
我觉得可以，图像处理算子我们还是比较丰富的，可以简单加几个在例子中，等我再修改的更规范一点

2020-09-18 01:45 UTC, MARD1NO commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +- 通过调用 OpenCV 库的 `imdecode` 方法对读取到的**字节流数据**进行解码，**转换成原始图片数据**
好的，我再修改下

2020-09-18 01:46 UTC, MARD1NO commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +完整代码：[img2ofrecord.py](NULL)
> labels 2W 条数据太多了，而且它的地位和原始图片是一样的吧，应该放到oss上，而不是github上。
> 另外labels现在的格式是一行代表一个label，行号对应了文件index？这个用户比较难抽查是否lable正确。
> 可以改成：
> 
> ```
> file1,label1
> file2,label2
> ...
> ```
> 
> 这样或其它格式

我整成一个哈希表怎么样？键是文件名，对应的值是label

2020-09-21 01:32 UTC, MARD1NO commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +OneFlow 内部的解码算子是采用 [OpenCV](https://opencv.org/) 来对数据进行解码的。相关的 `.cpp` 文件在 [oneflow.user.kernels.ofrecord_decoder_kernels.cpp](https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/user/kernels/o
编码格式这块我不太会写。。可能后续我们得开个会议说下这事儿

2020-09-24 03:08 UTC, MARD1NO reviewed
已修改

2020-09-24 03:14 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +
这个空行（以及下面的那个空行）应该不是必须的？

2020-09-24 03:17 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +<<<<<<< HEAD
貌似多余的？

2020-09-24 04:07 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +# 制作OFRecord数据集
标题应该是“将图片文件制作为 OFRecord 数据集”。
另外，这篇文章是偏工具的（原理的其它文件已经介绍，而且这篇文件的重点就是给用户提供了个能用能改的脚本），所以后面的一些建议都是从这个角度触发的。

2020-09-24 04:08 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +本文，我们将围绕 OneFlow 的 OFRecord 数据集的编解码方式与制作展开，包括：
本文，将介绍如何将图片文件制作为 OFRecord 数据集。

2020-09-24 04:09 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +在 [OFrecord数据格式](./ofrecord.md) 和 [加载与准备 OFRecord 数据集](./how_to_make_ofdataset.md) 中，我们分别学习了 OFRecord 文件的存储格式以及如何加载 OFRecord 数据集。
分别学习了如何将其它数据集格式转为 OFRecord 数据集，以及如何加载 OFRecord 数据集。（存储格式是另外一篇文章）

2020-09-24 04:10 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +本文，我们将围绕 OneFlow 的 OFRecord 数据集的编解码方式与制作展开，包括：
并提供了相关的制作脚本，方便用户直接使用或者在此基础上修改。

2020-09-24 04:12 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +## 完整代码
标题忘记删除了？

2020-09-24 04:16 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +
脚本的使用应该放在最前面。告之用户:"此处可以下载将图片转为 ofrecord 数据集的脚本以及对应的示例文件“。然后介绍目录结构（下文有）、label格式（下文没有）、脚本命令行参数说明（下文没有）。

2020-09-24 08:28 UTC, doombeaker commented on cn/docs/extended_topics/how_to_convert_image_to_ofrecord.md
> +$ cd ./img_to_ofrecord
这个把命令和显示放到一起，对初级读者而言，可能显得比较复杂，可以拆开。
比如：
下载相关压缩包并解压：
```
wget  https://oneflow-static.oss-cn-beijing.aliyuncs.com/oneflow-tutorial-attachments/img2ofrecord.zip
unzip img2ofrecord.zip
```
切换到对应目录，并运行制作脚本：
```
cd ./img_to_ofrecord
python img2ofrecord.py --part_num=5 --save_dir=./dataset/ --img_format=.png --image_root=./images/train_set/
```
脚本运行过程中，将输出类似以下内容：
```
The image root is:  ./images/train_set/
The amount of OFRecord data part is:  5
The directory of Labels is:  ./images/train_label/label.txt
The image format is:  .png
The OFRecord save directory is:  ./dataset/
Start Processing......
./images/train_set/00000030_3.png feature saved
./images/train_set/00000034_0.png feature saved
./images/train_set/00000026_4.png feature saved
./images/train_set/00000043_9.png feature saved
......
Process image successfully !!!
```

2020-09-24 08:29 UTC, doombeaker approved these changes

2020-09-24 08:43 UTC, merged