Update how_to_convert_image_to_ofrecord.md
Oneflow-Inc/oneflow-documentation pull request #268
Opened 2020-11-02 09:50 UTC by Ziheng-ZHAO

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/consistent_mirrored.md
each training nodes -> each training node

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/consistent_mirrored.md
百度了下 in detail 表示详细地， in details 指各个细节。我感觉这里两者都可以，改不改可以自己斟酌下

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/consistent_mirrored.md
following 和 later 感觉有点重复

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/debug_by_vscode.md
it is not recommended to do 这句语法是错误的
可以改成 it is recommended that xxxxx，后面的自己变一下

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/how_to_convert_image_to_ofrecord.md
data set -> dataset

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/how_to_make_ofdataset.md
我觉得把后面那句 we also 拆成 Also，we xxx 会好一点

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/how_to_make_ofdataset.md
`OFRecord file `    file 后面多了个空格

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/how_to_make_ofdataset.md
we show -> we have shown

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/how_to_make_ofdataset.md
> +The benefit of using `ofrecord_reader` is that `ofrecord_reader` acts as a normal operator which participates in OneFlow composition optimization and enjoys OneFlow flowline acceleration.
flowline 改成 pipeline

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/how_to_make_ofdataset.md
108行这里“-” 后面多了个空格。

另外refer前面加点词比较好，比如you can refer to xxx, please refer to xxx

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/model_mixed_parallel.md
between the two 改成 between them 或者 between the two views are

2020-11-04 12:48 UTC, MARD1NO commented on en/docs/extended_topics/model_mixed_parallel.md
>  Besides the model parallelism, OneFlow also provides a more flexible parallelism method called pipelining, it allow user use  `scope.placement` to specify the device of the operator.
use 后面多了个空格

2020-11-09 13:09 UTC, MARD1NO requested changes

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/basics_topics/distributed_train.md
> +> If there is a virtual network cards, you may not be able to communicate with nccl. In this case, you need to specify the communication network cards by `export NCCL_SOCKET_IFNAME=device_name`. More
there is a -> there are 因为你后面是cards

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/basics_topics/model_load_save.md
> +
这么多换行是为什么

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/basics_topics/model_load_save.md
load 后面多了空格

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/basics_topics/model_load_save.md
> +The finely tuned models are saved in `. /mlp_ext_models_1`.
The finely tuned -> The finetuned

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/basics_topics/optimizer_in_function_config.md
> +
so no parameter is passed to `function_config` -> so there is no parameter passed to `function_config`

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/basics_topics/optimizer_in_function_config.md
> +Because OneFlow will back propagates for `train` functions. Thus you need to specify the following settings like optimizer, learning rate and other hyperparameters in the job function.
will back propagates -> will back propagate

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/basics_topics/optimizer_in_function_config.md
> +Because OneFlow will back propagates for `train` functions. Thus you need to specify the following settings like optimizer, learning rate and other hyperparameters in the job function.
Because 和 Thus 不能连用

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/extended_topics/watch_watch_diff.md
> +* At the appropriate time when the job function is running, the OneFlow will call the previous callback which was registered earlier and pass the monitored data to the callback function then execute
OneFlow 前面的 the 去掉

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/extended_topics/watch_watch_diff.md
> +* At the appropriate time when the job function is running, the OneFlow will call the previous callback which was registered earlier and pass the monitored data to the callback function then execute
previous callback 后面加个 function

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/quick_start/lenet_mnist.md
> +Modules  [oneflow.nn](https://oneflow.readthedocs.io/en/master/nn.html) and [oneflow.layers](https://oneflow.readthedocs.io/en/master/layers.html)  provide the operators to construct the model.
[oneflow.nn] 前面多了空格, 类似这些需要自己注意

2020-11-09 13:09 UTC, MARD1NO commented on en/docs/quick_start/lenet_mnist.md
> +OneFlow provides a decorator named  [oneflow.global_function](https://oneflow.readthedocs.io/en/master/oneflow.html#oneflow.global_function)  by which we can covert a Python function to a OneFlow **J
同样的问题,后面也有一些多余的空格

2020-11-16 08:34 UTC, Ziheng-ZHAO commented on en/docs/basics_topics/build_nn_with_op_and_layer.md
> +When the job function is run, `data` is in shape of `100x1×28×28`. `data` is firstly used as input in `conv2d` to participate in the convolution calculation and obtained the result `conv1` then `conv
`Data` is firstly used as input in `conv2d` to participate in the convolution calculation and  the result from `conv1` is passed to `max_pool2d` as input. 这么说可以吗

2020-11-30 01:32 UTC, doombeaker approved these changes

2020-11-30 01:33 UTC, merged