Global Tensor 分布式并行策略
Oneflow-Inc/oneflow-documentation pull request #512
Opened 2022-08-04 07:05 UTC by lmyybh

列出《分布式并行策略》文章相关的思路以及部分内容

TODO:
- [ ] 添加作者
- [ ] 代码测试
- [ ] 完善内容

2022-08-04 08:34 UTC, doombeaker reviewed
之前开会的时候，我们的建议是“先列一个精确到二级标题的大纲，然后我们讨论下结构”。

现在直接出了一个初稿的，但是我觉得整体的方向是不对的。我觉得可能需要某种意义上的推倒重来。

并且建议阅读下 https://github.com/Oneflow-Inc/OneTeam/blob/master/tutorial/oneflow_docs_system.md

我的建议是：
1. 先忘记这篇初稿，回退到 “整理大纲” 的阶段，重新整理下大纲
2. 做以上工作时，注意 “这是一篇 how to”
3. 整理大纲时，可以先不写具体代码，但是可以写一下自己想用哪类 demo 的例子，方便我和啸宇等讨论、给建议（比如简单说想用 matmul 的例子，我就能给出自己的观点，觉得离实际工作较远）

2022-08-04 08:34 UTC, doombeaker commented on cn/docs/cookies/global_tensor_distributed.md
> +本文以矩阵乘法为例，解释并行策略间的区别，以及如何利用 Global Tensor 实现不同的并行方式。
这个定位不大符合我最开始的想法（当然这个没关系，我们就是要通过这个PR和讨论达成统一）。

这篇文档的定位是 “how to”， how to 是”解决问题为导向“的，强调实际操作和解决工作中的问题。

用 `matmul` 显得离实际工作比较远。“分布式专题”中谈策略，用 matmul，是因为定位是 tuotrial（具体见下图）。

这里举例，建议不要用 matmul，而用 **具体的网络模型** （可以很小，但是是一个完整的模型比较好）

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/3351623/182799741-0ec3b23d-434b-4c52-a5e0-32e3427eeab9.png">

2022-08-04 08:34 UTC, doombeaker commented on cn/docs/cookies/global_tensor_distributed.md
> +修改后，完整代码如下：
这里只提供了代码，没有谈如何启动，不符合“重实践”。可能用户直接复制这类代码去跑，会发现跑不起来。

（你跑过这些代码么……）

2022-08-04 08:34 UTC, doombeaker commented on cn/docs/cookies/global_tensor_distributed.md
> +>> 当数据集较大，模型较小时，由于反向过程中为同步梯度产生的通信代价较小，此时选择数据并行一般比较有优势，常见的视觉分类模型，如 ResNet50，比较适合采用数据并行。
这些介绍又太偏 tutorial 了。其实感觉可以不放。或者说放的话，也要用 how to 的风格，体现实践和面向解决工作中的问题。比如，列出 ResNet50 这类模型用数据并行的线性加速比（效果好），再列出 BERT 那类模型用数据并行的线性加速比（效果不好）

2022-08-04 08:48 UTC, lmyybh commented on cn/docs/cookies/global_tensor_distributed.md
> +修改后，完整代码如下：
代码还没有测试，所以启动部分没写，我想的是代码量也不大，就放上来展示一下

2022-08-04 08:51 UTC, lmyybh commented on cn/docs/cookies/global_tensor_distributed.md
> +本文以矩阵乘法为例，解释并行策略间的区别，以及如何利用 Global Tensor 实现不同的并行方式。
上次开会其实有提到用 matmul 做示例，不过我写的时候，尤其是流水并行那里，确实觉得 matmul 和实际应用相差有点大，换一个 nn.Module 模型效果会更好

2022-08-04 10:21 UTC, strint commented on cn/docs/cookies/global_tensor_distributed.md
> +本文以矩阵乘法为例，解释并行策略间的区别，以及如何利用 Global Tensor 实现不同的并行方式。
因为 nn.Module 需要用到 nn.Module 上的 to_global api，如果要用的话，需要单独写一小节

2022-08-04 10:23 UTC, strint commented on cn/docs/cookies/global_tensor_distributed.md
> +### 混合并行
混合并行这里考虑知识跨度，可以把三个例子组合起来就好，而不写复杂而具体的case。

实际使用中，混合并行需要用到 2D sbp，可以开单独的一篇文章。

2022-08-05 01:31 UTC, lmyybh commented on cn/docs/cookies/global_tensor_distributed.md
> +### 混合并行
三个例子组合起来是用 matmul 再给一个程序吗？混合并行这里两两混合和三种全用应该总共有四种混合方式，需要全放上例子吗？

2022-08-05 02:26 UTC, strint commented on cn/docs/cookies/global_tensor_distributed.md
> +### 混合并行
可以不用做复杂组合，一个case就可以了。需要放上例子。

2022-08-08 06:18 UTC, lmyybh commented
通过 `python3 -m oneflow.distributed.launch --nproc_per_node 2 test.py` 运行下面程序时：

```python
# test.py
import oneflow as flow

placement = flow.placement(type="cpu", ranks=[0, 1])
x = flow.randn(4, 5, placement=placement, sbp=flow.sbp.split(dim=0))
w = flow.randn(5, 8, placement=placement, sbp=flow.sbp.broadcast)
out = flow.matmul(x, w)
print(out.shape) # (4, 8)
```

输出如下：
```
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
W20220808 14:14:29.378463 17476 rpc_client.cpp:190] LoadServer 127.0.0.1 Failed at 0 times error_code 14 error_message failed to connect to all addresses
oneflow.Size([4, 8])
oneflow.Size([4, 8])
```

会出现个报错 `LoadServer 127.0.0.1 Failed at 0 times error_code 14 error_message failed to connect to all addresses` ，应该怎么避免？

2022-08-08 08:40 UTC, strint commented
> LoadServer 127.0.0.1 Failed at 0 times error_code 14 error_message failed to connect to all addresses ，应该怎么避免？

这个是提示，多机在建立连接，等一下就好了

2022-08-19 09:46 UTC, strint commented on cn/docs/cookies/global_tensor_distributed.md
> +```
这个例子，再增加一个 nn.Graph 的版本来跑通执行吧

2022-08-19 09:49 UTC, strint commented on cn/docs/cookies/global_tensor_distributed.md
> +```
辅助参考资料：https://docs.oneflow.org/master/parallelism/06_pipeline.html

2022-08-22 08:20 UTC, doombeaker commented on cn/docs/cookies/distributed_outline.md
> +
这篇 outline 记得在合并前需要删除。必要合并到仓库里去了。

另外，现在因为还没有修改 `mkdocs.yml` 文件，新增其实文章也不会真正的显示到网站上去的。

你参照其它新增文章的 PR，修改下 `mkdocs.yml` 文件，并本地 `mkdocs build` 查看下效果吧。

把最终的结果贴图下，这样方便排查一些编译html时产生的格式问题。

2022-08-22 09:47 UTC, strint commented on cn/docs/cookies/global_tensor_distributed.md
> +class ModuleModel(nn.Module):
上面的 eager 是不是也可以复用这个

2022-08-22 09:54 UTC, strint approved these changes

2022-08-22 09:56 UTC, strint approved these changes

2022-08-22 09:57 UTC, doombeaker requested changes
记得修改 mkdocs.yml 和 添加 html 的截图。
后续我再找人翻译英文版。

2022-08-23 07:40 UTC, lmyybh commented
页面展示：

![distributed](https://user-images.githubusercontent.com/38728055/186100298-3af51fef-f986-4260-b329-124e79518cac.png)

2022-08-31 03:31 UTC, lmyybh commented on en/docs/cookies/global_tensor_distributed.md
> +**Note: If you don’t have multiple GPUs, you can designate the `placement` as `type="cpu"` in the third line of the following code, so you can simulate multi-device parallelism with CPUs.**
```suggestion
**Note: If you don’t have multiple GPUs, you can simulate multi-device parallelism with CPUs via designating the `placement` as `type="cpu"`.**
```

2022-08-31 03:34 UTC, lmyybh reviewed
英文版本里的示例代码可以加一些空行把不同功能的代码段隔开，便于阅读

2022-09-05 02:04 UTC, doombeaker commented on en/docs/cookies/global_tensor_distributed.md
> +**Note: If you don’t have multiple GPUs, you can designate the `placement` as `type="cpu"` in the third line of the following code, so you can simulate multi-device parallelism with CPUs.**
@Jiachuann

2022-09-05 03:04 UTC, strint commented on en/docs/cookies/global_tensor_distributed.md
> +# Using Global Tensor for Multi-Device Multi-GPU Programming: Distributed Parallelism Strategies
> Multi-Device Multi-GPU

"多机多设备编程"，现在感觉太啰嗦了，可以改了 “分布式编程”，这里翻译需要调整为 distributed programming

请帮忙把这两篇文章都改一下：
- 使用 Global Tensor 进行多机多设备编程：基础操作: cookies/global_tensor.md
- 使用 Global Tensor 进行多机多设备编程：分布式并行策略: cookies/global_tensor_distributed.md

2022-09-05 14:23 UTC, strint commented on en/mkdocs.yml
> +      - Using Global Tensor to Program on Multi-Device Multi-GPU: Basic Operations: cookies/global_tensor.md
这里也需要改下

2022-09-05 14:26 UTC, strint commented on en/docs/cookies/global_tensor.md
> +# Using Global Tensor for Distributed Programming: Basic Operations
-> Distributed Programming with Global Tensor ?

2022-09-05 14:26 UTC, strint commented on en/docs/cookies/global_tensor_distributed.md
> +# Using Global Tensor for Distributed Programming: Distributed Parallelism Strategies
-> Distributed Programming with Global Tensor ?

2022-09-08 08:17 UTC, doombeaker approved these changes

2022-09-08 08:18 UTC, merged